### ISSUE TITLE
TH 9 recognise as TH8

### ISSUE THREAD

**Issue by frriction** [LunaEclipse73/MyBot.run-Extreme-DE-Side-MOD#11]
Here is log
http://pastebin.com/sm7TCatq

I am using v1.02

**Comment by LunaEclipse73** [comment]
This is a known issue with the official bot, and something we can't fix, we need to wait for them to fix it.

Check https://mybot.run/forums/thread-11914.html for a list of known bot problems and links to the threads with information.  Town hall detection has not been solved yet.

**Comment by frriction** [comment]
ok thanks for info.
